### ISSUE TITLE
Github actions terraform

### ISSUE THREAD

**Issue by jakubkozera** [mifurm/AZNetWorkshop#1]
hej @mifurm 

Żeby nie zgineło pytanie, jak masz jakiś przykład użycia terraforma w GA, to podeślij :p

**Comment by mifurm** [comment]
> 

Proszę! https://github.com/mifurm/devops01. Nic wielkiego ale jest :)

**Comment by jakubkozera** [comment]
thx :)

**Comment by mifurm** [comment]
done
